apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workflow-operator
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - exocortex.com
  resources:
  - workflows
  verbs:
  - '*'
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - '*'
