apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-controller
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - '*'
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - '*'
